#!/usr/bin/env bash
# ----------- daniel -------------
# Immich fork — this entire file is ours.
#
# Installs the mobile build toolchain into /usr/src/app/.mobile-tools, which is
# bind-mounted (survives devcontainer rebuilds) and gitignored. Wired as
# postCreateCommand in .devcontainer/mobile/devcontainer.json, so a fresh clone
# is provisioned automatically on container build.
#
# Idempotent: each component is skipped when already present, so re-runs (e.g.
# a plain "Rebuild Container") finish in seconds.
#
# Why this exists: the mobile devcontainer image bakes Flutter 3.35.7 (too old
# for the project's Dart SDK), ships only a JRE (no javac), has no Android SDK,
# and does not include mise. See FORK_CHANGES.md.
set -euo pipefail

ROOT=/usr/src/app/.mobile-tools

# Keep FLUTTER_VERSION in sync with mobile/mise.toml.
FLUTTER_VERSION=3.41.9
ANDROID_PLATFORM=android-36      # Flutter compileSdk default for this Flutter
ANDROID_BUILD_TOOLS=36.0.0
CMDLINE_TOOLS_ZIP=commandlinetools-linux-11076708_latest.zip

log() { echo ">> [mobile-toolchain] $*"; }

mkdir -p "$ROOT"/{downloads,android-sdk,android-user,gradle,pub-cache}

# --- Temurin JDK 21 (image only ships a JRE) ------------------------------
if [ -x "$ROOT/jdk-21/bin/javac" ]; then
  log "JDK 21 present, skipping"
else
  log "Installing Temurin JDK 21..."
  mkdir -p "$ROOT/jdk-21"
  curl -sSL -o "$ROOT/downloads/jdk21.tar.gz" \
    "https://api.adoptium.net/v3/binary/latest/21/ga/linux/x64/jdk/hotspot/normal/eclipse"
  tar -xzf "$ROOT/downloads/jdk21.tar.gz" --strip-components=1 -C "$ROOT/jdk-21"
fi
export JAVA_HOME="$ROOT/jdk-21"

# --- Android SDK command-line tools ---------------------------------------
SDKM="$ROOT/android-sdk/cmdline-tools/latest/bin/sdkmanager"
if [ -x "$SDKM" ]; then
  log "Android cmdline-tools present, skipping"
else
  log "Installing Android command-line tools..."
  curl -sSL -o "$ROOT/downloads/cmdline-tools.zip" \
    "https://dl.google.com/android/repository/$CMDLINE_TOOLS_ZIP"
  rm -rf "$ROOT/downloads/cmdline-tools"
  unzip -q "$ROOT/downloads/cmdline-tools.zip" -d "$ROOT/downloads"
  mkdir -p "$ROOT/android-sdk/cmdline-tools"
  rm -rf "$ROOT/android-sdk/cmdline-tools/latest"
  mv "$ROOT/downloads/cmdline-tools" "$ROOT/android-sdk/cmdline-tools/latest"
fi

# --- Android SDK packages -------------------------------------------------
if [ -x "$ROOT/android-sdk/platform-tools/adb" ] \
  && [ -d "$ROOT/android-sdk/platforms/$ANDROID_PLATFORM" ] \
  && [ -d "$ROOT/android-sdk/build-tools/$ANDROID_BUILD_TOOLS" ]; then
  log "Android SDK packages present, skipping"
else
  log "Installing Android SDK packages (platform-tools, $ANDROID_PLATFORM, build-tools $ANDROID_BUILD_TOOLS)..."
  yes | "$SDKM" --sdk_root="$ROOT/android-sdk" --licenses >/dev/null 2>&1 || true
  "$SDKM" --sdk_root="$ROOT/android-sdk" \
    "platform-tools" "platforms;$ANDROID_PLATFORM" "build-tools;$ANDROID_BUILD_TOOLS"
fi

# --- Flutter (project-pinned version) -------------------------------------
if [ -x "$ROOT/flutter/bin/flutter" ] \
  && "$ROOT/flutter/bin/flutter" --version 2>/dev/null | grep -q "$FLUTTER_VERSION"; then
  log "Flutter $FLUTTER_VERSION present, skipping"
else
  log "Installing Flutter $FLUTTER_VERSION..."
  rm -rf "$ROOT/flutter"
  mkdir -p "$ROOT/flutter"
  curl -sSL -o "$ROOT/downloads/flutter.tar.xz" \
    "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz"
  tar -xf "$ROOT/downloads/flutter.tar.xz" --strip-components=1 -C "$ROOT/flutter"
fi
git config --global --add safe.directory "$ROOT/flutter"

# --- env.sh (gitignored — regenerated here so a fresh clone has it) -------
cat > "$ROOT/env.sh" <<'EOF'
# shellcheck shell=bash
# Generated by .devcontainer/mobile/install-mobile-toolchain.sh
# Flutter / Android SDK / JDK environment for the Immich mobile devcontainer.
# Active automatically after a devcontainer rebuild (devcontainer.json
# remoteEnv); source it manually in a shell started before the rebuild:
#     source /usr/src/app/.mobile-tools/env.sh
export FLUTTER_HOME=/usr/src/app/.mobile-tools/flutter
export JAVA_HOME=/usr/src/app/.mobile-tools/jdk-21
export ANDROID_HOME=/usr/src/app/.mobile-tools/android-sdk
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export ANDROID_USER_HOME=/usr/src/app/.mobile-tools/android-user
export GRADLE_USER_HOME=/usr/src/app/.mobile-tools/gradle
export PUB_CACHE=/usr/src/app/.mobile-tools/pub-cache
export PATH="$FLUTTER_HOME/bin:$JAVA_HOME/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
EOF

# --- Gradle memory caps (gitignored override of mobile/android/gradle.properties) -
# This devcontainer also runs the full Immich stack (server/db/redis/ML) on a
# ~8 GB host; the project's 4 GB Gradle + Kotlin heaps get OOM-killed. Compiling
# Kotlin in-process avoids a separate KotlinCompileDaemon JVM (the main cause).
cat > "$ROOT/gradle/gradle.properties" <<'EOF'
# Generated by .devcontainer/mobile/install-mobile-toolchain.sh
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=512m
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvmargs=-Xmx1536m
EOF

# --- project codegen (best-effort: leaves the app ready for `flutter run`) -
# The i18n generated files are not committed; build_runner output (*.g.dart)
# is committed, so only translations need generating here.
log "Resolving deps + i18n codegen (best-effort)..."
export PATH="$ROOT/flutter/bin:$JAVA_HOME/bin:$ROOT/android-sdk/platform-tools:$PATH"
export PUB_CACHE="$ROOT/pub-cache"
(
  cd /usr/src/app/mobile
  flutter pub get
  dart run easy_localization:generate -S ../i18n
  dart run bin/generate_keys.dart
) || log "WARN: codegen failed — run it manually (see FORK_CHANGES.md section 3)"

rm -rf "$ROOT/downloads"
log "Mobile toolchain ready at $ROOT"
